FROM python:3.11-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    gcc \
    git \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -ms /bin/bash vscode
USER vscode

# Install Poetry
ENV POETRY_HOME=/home/vscode/.poetry
ENV PATH=$POETRY_HOME/bin:$PATH
RUN curl -sSL https://install.python-poetry.org | python3 -

WORKDIR /workspace

CMD ["sleep", "infinity"]